name: Zip Datapack

on:
  push:
    branches:
      - master

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip Datapack
        run: |
          zip -r "Starter Items - Adventure Gear.zip" pack.mcmeta pack.png data/

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SI - Adventure Gear.zip
          path: Starter Items - Adventure Gear.zip
