name: Zip Datapack

on:
  push:
    branches:
      - master

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip Adventure Gear Kit
        run: |
          zip -r "Starter Items - Adventure Gear Kit.zip" pack.png adventure_gear_kit/pack.mcmeta adventure_gear_kit/data/

      - name: Zip Alchemist Starter Kit
        run: |
          zip -r "Starter Items - Alchemist Starter Kit.zip" pack.png alchemist_starter_kit/pack.mcmeta alchemist_starter_kit/data/

      - name: Zip Builder Starter Kit
        run: |
          zip -r "Starter Items - Builder Starter Kit.zip" pack.png builder_starter_kit/pack.mcmeta builder_starter_kit/data/

      - name: Zip Craftsman Starter Kit
        run: |
          zip -r "Starter Items - Craftsman Starter Kit.zip" pack.png craftsman_starter_kit/pack.mcmeta craftsman_starter_kit/data/

      - name: Zip Fisher Starter Kit
        run: |
          zip -r "Starter Items - Fisher Starter Kit.zip" pack.png fisher_starter_kit/pack.mcmeta fisher_starter_kit/data/

      - name: Zip Hunter Starter Kit
        run: |
          zip -r "Starter Items - Hunter Starter Kit.zip" pack.png hunter_starter_kit/pack.mcmeta hunter_starter_kit/data/

      - name: Zip Knight Starter Kit
        run: |
          zip -r "Starter Items - Knight Starter Kit.zip" pack.png knight_starter_kit/pack.mcmeta knight_starter_kit/data/

      - name: Zip Miner Starter Kit
        run: |
          zip -r "Starter Items - Miner Starter Kit.zip" pack.png miner_starter_kit/pack.mcmeta miner_starter_kit/data/

      - name: Zip Nomad Starter Kit
        run: |
          zip -r "Starter Items - Nomad Starter Kit.zip" pack.png nomad_starter_kit/pack.mcmeta nomad_starter_kit/data/

      - name: Zip Survival Starter Kit
        run: |
          zip -r "Starter Items - Survival Starter Kit.zip" pack.png survival_starter_kit/pack.mcmeta survival_starter_kit/data/

      - name: Upload Adventure Gear Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Adventure Gear Kit.zip
          path: Starter Items - Adventure Gear Kit.zip

      - name: Upload Alchemist Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Alchemist Starter Kit.zip
          path: Starter Items - Alchemist Starter Kit.zip

      - name: Upload Builder Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Builder Starter Kit.zip
          path: Starter Items - Builder Starter Kit.zip

      - name: Upload Craftsman Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Craftsman Starter Kit.zip
          path: Starter Items - Craftsman Starter Kit.zip

      - name: Upload Fisher Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Fisher Starter Kit.zip
          path: Starter Items - Fisher Starter Kit.zip

      - name: Upload Hunter Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Hunter Starter Kit.zip
          path: Starter Items - Hunter Starter Kit.zip

      - name: Upload Knight Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Knight Starter Kit.zip
          path: Starter Items - Knight Starter Kit.zip

      - name: Upload Miner Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Miner Starter Kit.zip
          path: Starter Items - Miner Starter Kit.zip

      - name: Upload Nomad Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Nomad Starter Kit.zip
          path: Starter Items - Nomad Starter Kit.zip

      - name: Upload Survival Starter Kit
        uses: actions/upload-artifact@v4
        with:
          name: SI - Survival Starter Kit.zip
          path: Starter Items - Survival Starter Kit.zip

